//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.Localization.LeagueOverlay {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LeagueOverlayResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LeagueOverlayResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.Localization.LeagueOverlay.LeagueOverlayResources", typeof(LeagueOverlayResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiled\nArmor.
        /// </summary>
        internal static string Betrayal_Aisling_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Aisling_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiled\nJewellery.
        /// </summary>
        internal static string Betrayal_Aisling_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Aisling_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Veiled\nMod(s).
        /// </summary>
        internal static string Betrayal_Aisling_Research {
            get {
                return ResourceManager.GetString("Betrayal_Aisling_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 1 Mod\nLevel2: Low Chance for 2 Mods\nLevel3: 2 Mods.
        /// </summary>
        internal static string Betrayal_Aisling_Research_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_Aisling_Research_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiled\nWeapons.
        /// </summary>
        internal static string Betrayal_Aisling_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Aisling_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harbinger\nOrbs.
        /// </summary>
        internal static string Betrayal_Cameria_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Cameria_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulphite\nScarab.
        /// </summary>
        internal static string Betrayal_Cameria_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Cameria_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sextants.
        /// </summary>
        internal static string Betrayal_Cameria_Research {
            get {
                return ResourceManager.GetString("Betrayal_Cameria_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeworn\nRelics.
        /// </summary>
        internal static string Betrayal_Cameria_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Cameria_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League Specific Items\n(Headhunter possible).
        /// </summary>
        internal static string Betrayal_Cameria_Transportation_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_Cameria_Transportation_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique\nArmor.
        /// </summary>
        internal static string Betrayal_Elreon_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Elreon_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliquary\nScarab.
        /// </summary>
        internal static string Betrayal_Elreon_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Elreon_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique\nJewellery.
        /// </summary>
        internal static string Betrayal_Elreon_Research {
            get {
                return ResourceManager.GetString("Betrayal_Elreon_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique\nWeapons.
        /// </summary>
        internal static string Betrayal_Elreon_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Elreon_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random\nDiv Cards.
        /// </summary>
        internal static string Betrayal_Gravicius_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Gravicius_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div Card\nScarab.
        /// </summary>
        internal static string Betrayal_Gravicius_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Gravicius_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap\nDiv Cards.
        /// </summary>
        internal static string Betrayal_Gravicius_Research {
            get {
                return ResourceManager.GetString("Betrayal_Gravicius_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div Card\nStack.
        /// </summary>
        internal static string Betrayal_Gravicius_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Gravicius_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essence\nCrafting.
        /// </summary>
        internal static string Betrayal_Guff_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Guff_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 Scouring\n5 * 4 Essences\n20 Exalted\n1 Vaal\nLevel1: 8 Seconds\nLevel2: 12 Seconds\nLevel3: 18 Seconds.
        /// </summary>
        internal static string Betrayal_Guff_Fortification_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_Guff_Fortification_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteration\nCrafting.
        /// </summary>
        internal static string Betrayal_Guff_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Guff_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Transmutation\n200 Alteration\n100 AUgmentation\n1 Regal\n1 Exalted\n1 Divine\n1 Vaal\nLevel1: 8 Seconds\nLevel2: 12 Seconds\nLevel3: 18 Seconds.
        /// </summary>
        internal static string Betrayal_Guff_Intervention_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_Guff_Intervention_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Alch\n100 Anullment\n100 Exalted\n1 Divine\n1 Blessed\n1 Vaal\nLevel1: 8 Seconds\nLevel2: 12 Seconds\nLevel3: 18 Seconds.
        /// </summary>
        internal static string Betrayal_Guff_Research_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_Guff_Research_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anull/Ex\nCrafting.
        /// </summary>
        internal static string Betrayal_Guff_Reserach {
            get {
                return ResourceManager.GetString("Betrayal_Guff_Reserach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos\nCrafting.
        /// </summary>
        internal static string Betrayal_Guff_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Guff_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Alch\n200 Chaos\n6 Exalted\n20 Divine\n20 Blessed\n1 Vaal\nLevel1: 8 Seconds\nLevel2: 12 Seconds\nLevel3: 18 Seconds.
        /// </summary>
        internal static string Betrayal_Guff_Transportation_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_Guff_Transportation_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongboxes.
        /// </summary>
        internal static string Betrayal_Haku_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Haku_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongbox\nScarab.
        /// </summary>
        internal static string Betrayal_Haku_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Haku_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality\nItems.
        /// </summary>
        internal static string Betrayal_Haku_Research {
            get {
                return ResourceManager.GetString("Betrayal_Haku_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare\nItems.
        /// </summary>
        internal static string Betrayal_Haku_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Haku_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor\nQuality.
        /// </summary>
        internal static string Betrayal_Hillock_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Hillock_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 24 %\nLevel2: 26 %\nLevel3: 28 %.
        /// </summary>
        internal static string Betrayal_Hillock_Fortification_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_Hillock_Fortification_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map\nQuality.
        /// </summary>
        internal static string Betrayal_Hillock_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Hillock_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 25 %\nLevel2: 30 %\nLevel3: 35 %.
        /// </summary>
        internal static string Betrayal_Hillock_Intervention_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_Hillock_Intervention_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flask\nQuality.
        /// </summary>
        internal static string Betrayal_Hillock_Research {
            get {
                return ResourceManager.GetString("Betrayal_Hillock_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 22 %\nLevel2: 24 %\nLevel3: 26%.
        /// </summary>
        internal static string Betrayal_Hillock_Research_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_Hillock_Research_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon\nQuality.
        /// </summary>
        internal static string Betrayal_Hillock_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Hillock_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 24 %\nLevel2: 26 %\nLevel3: 28%.
        /// </summary>
        internal static string Betrayal_Hillock_Transportation_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_Hillock_Transportation_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abyss\nJewels.
        /// </summary>
        internal static string Betrayal_ItThatFled_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_ItThatFled_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breach\nScarab.
        /// </summary>
        internal static string Betrayal_ItThatFled_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_ItThatFled_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade\nBreachstone.
        /// </summary>
        internal static string Betrayal_ItThatFled_Research {
            get {
                return ResourceManager.GetString("Betrayal_ItThatFled_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: Charged\nLevel2: Enriched\nLevel3: Pure.
        /// </summary>
        internal static string Betrayal_ItThatFled_Research_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_ItThatFled_Research_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breach\nSplinter.
        /// </summary>
        internal static string Betrayal_ItThatFled_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_ItThatFled_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency\nShards.
        /// </summary>
        internal static string Betrayal_Janus_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Janus_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perandus\nScarab.
        /// </summary>
        internal static string Betrayal_Janus_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Janus_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perandus\nCoins.
        /// </summary>
        internal static string Betrayal_Janus_Research {
            get {
                return ResourceManager.GetString("Betrayal_Janus_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality\nCurrency.
        /// </summary>
        internal static string Betrayal_Janus_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Janus_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestiary\nItems.
        /// </summary>
        internal static string Betrayal_Jorgin_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Jorgin_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestiary\nScarab.
        /// </summary>
        internal static string Betrayal_Jorgin_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Jorgin_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amulet to\nTalisman.
        /// </summary>
        internal static string Betrayal_Jorgin_Research {
            get {
                return ResourceManager.GetString("Betrayal_Jorgin_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: Level 1 Talisman\nLevel2: Level 2 Talisman\nLevel3: Level 3 Talisman.
        /// </summary>
        internal static string Betrayal_Jorgin_Research_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_Jorgin_Research_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talismans.
        /// </summary>
        internal static string Betrayal_Jorgin_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Jorgin_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map\nFragments.
        /// </summary>
        internal static string Betrayal_Korrel_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Korrel_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elder\nScarab.
        /// </summary>
        internal static string Betrayal_Korrel_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Korrel_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fossils.
        /// </summary>
        internal static string Betrayal_Korrel_Research {
            get {
                return ResourceManager.GetString("Betrayal_Korrel_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essences.
        /// </summary>
        internal static string Betrayal_Korrel_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Korrel_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random\nCurrency.
        /// </summary>
        internal static string Betrayal_Leo_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Leo_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torment\nScarab.
        /// </summary>
        internal static string Betrayal_Leo_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Leo_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency\nUse.
        /// </summary>
        internal static string Betrayal_Leo_Research {
            get {
                return ResourceManager.GetString("Betrayal_Leo_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: Blessed Orb\nLevel2: Divine Orb\nLevel3: Exalted Orb.
        /// </summary>
        internal static string Betrayal_Leo_Research_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_Leo_Research_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver\nCoins.
        /// </summary>
        internal static string Betrayal_Leo_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Leo_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take One\nUnique.
        /// </summary>
        internal static string Betrayal_Riker_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Riker_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take One\nDiv Card.
        /// </summary>
        internal static string Betrayal_Riker_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Riker_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take One\nVeiled.
        /// </summary>
        internal static string Betrayal_Riker_Research {
            get {
                return ResourceManager.GetString("Betrayal_Riker_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take One\nCurrency.
        /// </summary>
        internal static string Betrayal_Riker_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Riker_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare\nMaps.
        /// </summary>
        internal static string Betrayal_Rin_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Rin_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartography\nScarab.
        /// </summary>
        internal static string Betrayal_Rin_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Rin_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique\nMaps.
        /// </summary>
        internal static string Betrayal_Rin_Research {
            get {
                return ResourceManager.GetString("Betrayal_Rin_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal\nMaps.
        /// </summary>
        internal static string Betrayal_Rin_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Rin_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enchanted\nItems.
        /// </summary>
        internal static string Betrayal_Tora_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Tora_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: Gloves\nLevel2: Boots\nLevel3: Helmet.
        /// </summary>
        internal static string Betrayal_Tora_Fortification_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_Tora_Fortification_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harbinger\nScarab.
        /// </summary>
        internal static string Betrayal_Tora_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Tora_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gem\nExperience.
        /// </summary>
        internal static string Betrayal_Tora_Research {
            get {
                return ResourceManager.GetString("Betrayal_Tora_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 20m Exp\nLevel2: 70m Exp\nLevel3: 200m Exp.
        /// </summary>
        internal static string Betrayal_Tora_Research_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_Tora_Research_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Item\n[Timed].
        /// </summary>
        internal static string Betrayal_Tora_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Tora_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Limit: 8 Seconds\nCurrency\nDivination Cards\nUniques\nItem Level 100 Rare.
        /// </summary>
        internal static string Betrayal_Tora_Transportation_Tooltipü {
            get {
                return ResourceManager.GetString("Betrayal_Tora_Transportation_Tooltipü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare\nArmor.
        /// </summary>
        internal static string Betrayal_Vagan_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Vagan_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare\nJewels.
        /// </summary>
        internal static string Betrayal_Vagan_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Vagan_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare\nJewellery.
        /// </summary>
        internal static string Betrayal_Vagan_Research {
            get {
                return ResourceManager.GetString("Betrayal_Vagan_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare\nWeapons.
        /// </summary>
        internal static string Betrayal_Vagan_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Vagan_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linking\nCurrency.
        /// </summary>
        internal static string Betrayal_Vorice_Fortification {
            get {
                return ResourceManager.GetString("Betrayal_Vorice_Fortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaper\nScarab.
        /// </summary>
        internal static string Betrayal_Vorice_Intervention {
            get {
                return ResourceManager.GetString("Betrayal_Vorice_Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White\nSockets.
        /// </summary>
        internal static string Betrayal_Vorici_Research {
            get {
                return ResourceManager.GetString("Betrayal_Vorici_Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 1 White Socket\nLevel2: 1-2 White Sockets\nLevel3: 1-3 White Sockets.
        /// </summary>
        internal static string Betrayal_Vorici_Research_Tooltip {
            get {
                return ResourceManager.GetString("Betrayal_Vorici_Research_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality\nGems.
        /// </summary>
        internal static string Betrayal_Vorici_Transportation {
            get {
                return ResourceManager.GetString("Betrayal_Vorici_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Valuable.
        /// </summary>
        internal static string Legend_LessValuable {
            get {
                return ResourceManager.GetString("Legend_LessValuable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Valuable.
        /// </summary>
        internal static string Legend_NotValuable {
            get {
                return ResourceManager.GetString("Legend_NotValuable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuable.
        /// </summary>
        internal static string Legend_Valuable {
            get {
                return ResourceManager.GetString("Legend_Valuable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Valuable.
        /// </summary>
        internal static string Legend_VeryValuable {
            get {
                return ResourceManager.GetString("Legend_VeryValuable", resourceCulture);
            }
        }
    }
}
